### ISSUE TITLE
Compile_gc in Octave

### ISSUE THREAD

**Issue by Ingrid1989** [shaibagon/GCMex#2]
I'm trying to run the compile_gc file, in order to use this wrapper in octave (free version of matlab). 
But it keeps showing me the same error over and over again:
graph.h:47:10: fatal error: tmwtypes.h: No such file or directory
   47 | #include <tmwtypes.h>
      |          ^~~~~~~~~~~~
Indeed there is no such file, but apparently the graph.h function uses this. 
How can I fix this error?

p.s. complete error/warning is shown in the textfile below. 
[Compile_gc_error.txt](https://github.com/shaibagon/GCMex/files/5068606/Compile_gc_error.txt)

**Comment by shaibagon** [comment]
@Ingrid1989 hi,
Thank you for your interest in my code.  
I'm afraid [`tmwtypes.h`](https://in.mathworks.com/matlabcentral/answers/436220-what-is-tmwtypes-h-and-how-do-i-fix-an-error-of-it-not-being-seen-also-general-coder-questions#answer_357399) is part of Matlab and I don't know what is the "octave-equivalent" of it.

If you want to have an octave version of the code, you'll need to replace this header and probably do some serious re-write to the code.

-Shai

**Comment by Ingrid1989** [comment]
@shaibagon 

Thank you for the quick response. Now I at least now what I'm searching for.
